name: SonarCloud Analysis and Publish customer-app_domain + notifications_domain

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud-and-npm-publish:
    name: SonarCloud + NPM Package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@${{ github.repository_owner }}'

      # ========================
      # ğŸ”¹ NOTIFICATIONS
      # ========================
      - name: ğŸ“¦ Instalar dependencias - notifications
        working-directory: notifications
        run: npm ci

      - name: ğŸ§ª Ejecutar pruebas unitarias - notifications
        working-directory: notifications
        run: npm run test:cov

      - name: â˜ï¸ SonarCloud Scan - notifications
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          projectBaseDir: notifications
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: ğŸ”„ Versionar y publicar - notifications/libs/domain
        working-directory: notifications/libs/domain
        run: |
          VERSION="1.0.$(date +%s)"
          npm version "$VERSION" --no-git-tag-version
          echo "ğŸ“¦ Notif. versiÃ³n: $VERSION"
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ========================
      # ğŸ”¹ CUSTOMER-APP
      # ========================
      - name: ğŸ“¦ Instalar dependencias - customer-app
        working-directory: customer-app
        run: npm ci

      - name: ğŸ§ª Ejecutar pruebas unitarias - customer-app
        working-directory: customer-app
        run: npm run test:cov

      - name: â˜ï¸ SonarCloud Scan - customer-app
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          projectBaseDir: customer-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: ğŸ”„ Versionar y publicar - customer-app/libs/domain
        working-directory: customer-app/libs/domain
        run: |
          VERSION="1.0.$(date +%s)"
          npm version "$VERSION" --no-git-tag-version
          echo "ğŸ“¦ Customer versiÃ³n: $VERSION"
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
